import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const strings = {
  "ui.game.title": ["PXWORLD", "PXWORLD"],
  "ui.game.subtitle": ["Cổ Vật Hoàng Hôn", "Relic of the Dusk"],
  "ui.common.back": ["Quay lại", "Back"],
  "ui.common.cancel": ["Hủy", "Cancel"],
  "ui.common.close": ["Đóng", "Close"],
  "ui.common.continue": ["Tiếp tục", "Continue"],
  "ui.common.details": ["Chi tiết", "Details"],
  "ui.common.next": ["Tiếp", "Next"],
  "ui.error.rule": ["Không thể thực hiện: {0}", "Not allowed: {0}"],
  "ui.menu.continue": ["Chơi tiếp", "Continue"],
  "ui.menu.new_game": ["Chơi mới", "New game"],
  "ui.menu.load": ["Chọn bản lưu", "Load game"],
  "ui.menu.debug": ["Công cụ debug", "Debug tools"],
  "ui.menu.exit": ["Thoát", "Exit"],
  "ui.slots.title": ["Bản lưu", "Saved games"],
  "ui.slots.summary": ["Cấp {0} | {1} | {2} anh hùng", "Level {0} | {1} | {2} heroes"],
  "ui.slots.play": ["Chơi", "Play"],
  "ui.slots.delete": ["Xóa", "Delete"],
  "ui.slots.delete_title": ["Xóa bản lưu?", "Delete save?"],
  "ui.slots.delete_warning": ["Bản lưu \"{0}\" và các bản sao lưu của nó sẽ bị xóa vĩnh viễn.", "Save \"{0}\" and its backups will be deleted permanently."],
  "ui.slots.deleted": ["Đã xóa {0}", "Deleted {0}"],
  "ui.slots.corrupt": ["Bản lưu {0} bị hỏng", "Save {0} is corrupted"],
  "ui.create.class_title": ["Chọn anh hùng khởi đầu", "Choose your first hero"],
  "ui.create.choose": ["Chọn", "Choose"],
  "ui.create.power": ["Lực chiến {0}", "Power {0}"],
  "ui.create.name_title": ["Đặt tên", "Name your legend"],
  "ui.create.name_hint": ["Tên người chơi", "Player name"],
  "ui.create.name_rule": ["Tên dài {0}–{1} ký tự", "Name must be {0}–{1} characters"],
  "ui.create.confirm_title": ["Sẵn sàng lên đường", "Ready to set out"],
  "ui.create.confirm_summary": ["{0} cùng {1} ({2}) bắt đầu hành trình ở Làng Bình Minh.", "{0} and {1} ({2}) begin their journey in Dawn Village."],
  "ui.create.start": ["Bắt đầu", "Begin"],
  "ui.create.welcome": ["Chào mừng, {0}!", "Welcome, {0}!"],
  "ui.world.level": ["Cấp {0}", "Level {0}"],
  "ui.world.menu": ["Menu", "Menu"],
  "ui.world.inspect_enemy": ["Kiểm tra kẻ địch", "Inspect enemies"],
  "ui.world.travel": ["Đi tới {0}", "Travel to {0}"],
  "ui.world.travel_blocked": ["Lối đi này chưa mở", "This path is not open yet"],
  "ui.encounter.recommended": ["Cấp đề nghị {0}", "Recommended level {0}"],
  "ui.encounter.enemy_level": ["Cấp {0} | {1} sao", "Level {0} | {1} star"],
  "ui.encounter.rewards": ["Phần thưởng", "Rewards"],
  "ui.encounter.team": ["Đội của bạn: {0} anh hùng | Kẻ địch: {1}", "Your team: {0} heroes | Enemies: {1}"],
  "ui.encounter.fight": ["Chiến đấu", "Fight"],
  "ui.pause.title": ["Menu", "Menu"],
  "ui.pause.heroes": ["Anh hùng", "Heroes"],
  "ui.pause.lineup": ["Đội hình", "Lineup"],
  "ui.pause.bag": ["Túi đồ", "Bag"],
  "ui.pause.shop": ["Cửa hàng", "Shop"],
  "ui.pause.recruit": ["Chiêu mộ", "Recruit"],
  "ui.pause.checkin": ["Điểm danh", "Check-in"],
  "ui.pause.quests": ["Nhiệm vụ", "Quests"],
  "ui.pause.achievements": ["Thành tựu", "Achievements"],
  "ui.pause.settings": ["Cài đặt", "Settings"],
  "ui.pause.main_menu": ["Lưu và về menu chính", "Save and return to main menu"],
  "ui.pause.resume": ["Tiếp tục chơi", "Resume"],
  "ui.battle.auto_on": ["Tự động: bật", "Auto: on"],
  "ui.battle.auto_off": ["Tự động: tắt", "Auto: off"],
  "ui.battle.auto_running": ["Đang tự động chiến đấu...", "Auto battle running..."],
  "ui.battle.enemy_turn": ["Lượt của kẻ địch...", "Enemy turn..."],
  "ui.battle.log": ["Nhật ký", "Log"],
  "ui.battle.flee": ["Bỏ chạy", "Flee"],
  "ui.battle.pick_target": ["Chọn mục tiêu", "Pick a target"],
  "ui.battle.round": ["Vòng {0}", "Round {0}"],
  "ui.battle.miss": ["Trượt", "Miss"],
  "ui.battle.resisted": ["Kháng", "Resisted"],
  "ui.battle.stunned": ["Choáng", "Stunned"],
  "ui.result.victory": ["Chiến thắng", "Victory"],
  "ui.result.defeat": ["Thất bại", "Defeat"],
  "ui.result.draw": ["Hòa", "Draw"],
  "ui.result.rounds": ["Kết thúc sau {0} vòng", "Finished after {0} rounds"],
  "ui.result.level_up": ["{0} lên cấp {1}", "{0} reached level {1}"],
  "ui.result.profile_level_up": ["Tài khoản lên cấp {0}", "Account reached level {0}"],
  "ui.result.quest_completed": ["Hoàn thành nhiệm vụ: {0}", "Quest complete: {0}"],
  "ui.result.nothing": ["Không nhận được gì", "Nothing gained"],
  "ui.result.retry": ["Đánh lại", "Retry"],
  "ui.heroes.title": ["Anh hùng", "Heroes"],
  "ui.heroes.overview_title": ["Thông tin anh hùng", "Hero details"],
  "ui.heroes.edit_lineup": ["Sửa đội hình", "Edit lineup"],
  "ui.heroes.level_star": ["Cấp {0} | {1} sao", "Level {0} | {1} star"],
  "ui.heroes.power": ["Lực chiến {0}", "Power {0}"],
  "ui.heroes.in_lineup": ["Trong đội hình", "In lineup"],
  "ui.heroes.experience": ["Kinh nghiệm {0}/{1}", "Experience {0}/{1}"],
  "ui.heroes.stats": ["Chỉ số", "Stats"],
  "ui.heroes.skills": ["Kỹ năng", "Skills"],
  "ui.heroes.equipment": ["Trang bị", "Equipment"],
  "ui.heroes.empty_slot": ["Trống", "Empty"],
  "ui.heroes.change": ["Đổi", "Change"],
  "ui.heroes.unequip": ["Tháo", "Unequip"],
  "ui.heroes.star_up": ["Tăng sao", "Raise star"],
  "ui.heroes.star_up_rule": ["Ghép một bản sao {0} cùng {1} sao để tăng sao. Bản sao sẽ mất đi, trang bị của nó được tháo ra.", "Merge another {0} at {1} sao to raise its star. The copy is consumed and its gear is unequipped."],
  "ui.heroes.star_up_none": ["Chưa có bản sao phù hợp", "No matching copy yet"],
  "ui.heroes.consume": ["Ghép", "Merge"],
  "ui.heroes.star_up_done": ["Đã tăng sao!", "Star raised!"],
  "ui.lineup.title": ["Đội hình", "Lineup"],
  "ui.lineup.capacity": ["{0}/{1} vị trí", "{0}/{1} slots"],
  "ui.lineup.back": ["Hàng sau", "Back"],
  "ui.lineup.middle": ["Hàng giữa", "Middle"],
  "ui.lineup.front": ["Hàng trước", "Front"],
  "ui.lineup.bench": ["Anh hùng", "Heroes"],
  "ui.lineup.assign": ["Xếp vào ô", "Place"],
  "ui.lineup.clear": ["Bỏ khỏi ô", "Clear cell"],
  "ui.bag.title": ["Túi đồ", "Bag"],
  "ui.bag.equipment": ["Trang bị", "Equipment"],
  "ui.bag.items": ["Vật phẩm", "Items"],
  "ui.bag.empty": ["Túi trống", "Nothing here yet"],
  "ui.bag.choosing_for": ["Chọn trang bị cho {0}", "Choosing gear for {0}"],
  "ui.bag.worn_by": ["Đang mặc: {0}", "Worn by {0}"],
  "ui.bag.equip": ["Mặc", "Equip"],
  "ui.bag.equipped": ["Đã mặc trang bị", "Equipped"],
  "ui.bag.equip_to": ["Mặc cho", "Equip on"],
  "ui.bag.equipment_detail": ["Chi tiết trang bị", "Equipment"],
  "ui.bag.item_detail": ["Chi tiết vật phẩm", "Item"],
  "ui.bag.owned": ["Đang có {0}", "Owned {0}"],
  "ui.bag.material": ["Nguyên liệu chế tạo", "Crafting material"],
  "ui.bag.gives_experience": ["Cho {0} kinh nghiệm", "Grants {0} experience"],
  "ui.bag.use": ["Dùng", "Use"],
  "ui.bag.used": ["Đã dùng", "Used"],
  "ui.shop.title": ["Cửa hàng", "Shop"],
  "ui.shop.items": ["Vật phẩm", "Items"],
  "ui.shop.equipment": ["Trang bị", "Equipment"],
  "ui.shop.balance": ["Vàng {0} | Ngọc {1}", "Gold {0} | Gems {1}"],
  "ui.shop.buy": ["Mua", "Buy"],
  "ui.shop.confirm_title": ["Xác nhận mua", "Confirm purchase"],
  "ui.shop.bought": ["Đã mua {0}", "Bought {0}"],
  "ui.recruit.title": ["Chiêu mộ", "Recruit"],
  "ui.recruit.pool": ["Anh hùng có thể xuất hiện", "Heroes in this pool"],
  "ui.recruit.rates": ["Mỗi anh hùng có tỉ lệ bằng nhau (1/{0})", "Each hero has equal odds (1/{0})"],
  "ui.recruit.balance": ["Bạn có {0} {1}", "You have {0} {1}"],
  "ui.recruit.recruit": ["Chiêu mộ ({0} {1})", "Recruit ({0} {1})"],
  "ui.recruit.result_title": ["Anh hùng mới!", "New hero!"],
  "ui.recruit.again": ["Chiêu mộ tiếp", "Recruit again"],
  "ui.checkin.title": ["Điểm danh", "Daily check-in"],
  "ui.checkin.day": ["Ngày {0}", "Day {0}"],
  "ui.checkin.claim": ["Nhận quà ngày {0}", "Claim day {0}"],
  "ui.checkin.claimed_today": ["Hôm nay đã nhận", "Claimed today"],
  "ui.checkin.claimed": ["Đã nhận quà điểm danh", "Check-in reward claimed"],
  "ui.quests.title": ["Nhiệm vụ", "Quests"],
  "ui.quests.claim": ["Nhận thưởng", "Claim"],
  "ui.quests.claimed": ["Đã nhận thưởng", "Claimed"],
  "ui.quests.in_progress": ["Đang làm", "In progress"],
  "ui.achievements.title": ["Thành tựu", "Achievements"],
  "ui.achievements.tier": ["Bậc {0}/{1}", "Tier {0}/{1}"],
  "ui.achievements.complete": ["Hoàn tất", "Complete"],
  "ui.settings.title": ["Cài đặt", "Settings"],
  "ui.settings.music": ["Nhạc nền", "Music"],
  "ui.settings.sound": ["Hiệu ứng âm thanh", "Sound effects"],
  "ui.settings.on": ["Bật", "On"],
  "ui.settings.off": ["Tắt", "Off"],
  "ui.settings.language": ["Ngôn ngữ", "Language"],
  "ui.language.vi": ["Tiếng Việt", "Tiếng Việt"],
  "ui.language.en": ["English", "English"],
  "ui.slot.weapon": ["Vũ khí", "Weapon"],
  "ui.slot.armor": ["Giáp", "Armor"],
  "ui.slot.jewelry": ["Trang sức", "Jewelry"],
  "ui.slot.support": ["Phụ kiện", "Support"],
  "ui.stat.hp": ["Máu", "HP"],
  "ui.stat.attack": ["Tấn công", "Attack"],
  "ui.stat.defense": ["Phòng thủ", "Defense"],
  "ui.stat.speed": ["Tốc độ", "Speed"],
  "ui.stat.crit_rate": ["Tỉ lệ chí mạng", "Crit rate"],
  "ui.stat.crit_damage": ["Sát thương chí mạng", "Crit damage"],
  "ui.stat.accuracy": ["Chính xác", "Accuracy"],
  "ui.stat.evasion": ["Né tránh", "Evasion"],
  "ui.stat.effect_hit": ["Hiệu lực", "Effect hit"],
  "ui.stat.effect_resistance": ["Kháng hiệu ứng", "Effect resistance"],
  "ui.debug.title": ["Công cụ debug", "Debug tools"],
  "ui.debug.flavor": ["Bản build: {0}", "Build flavor: {0}"],
  "ui.debug.screen_jump": ["Nhảy tới màn hình", "Screen jump"],
  "ui.debug.cheats": ["Cheat", "Cheats"],
  "ui.debug.atlas_browser": ["Duyệt atlas", "Atlas browser"],
  "ui.debug.coverage": ["Đã có {0} màn | launch cần {1} | catalog {2}", "{0} screens built | launch needs {1} | catalog {2}"],
  "ui.debug.open": ["Mở", "Open"],
  "ui.debug.needs_game": ["Cần mở một bản lưu trước", "Load a game first"],
  "ui.debug.grant_gold": ["+10.000 vàng", "+10,000 gold"],
  "ui.debug.grant_gem": ["+1.000 ngọc", "+1,000 gems"],
  "ui.debug.grant_food": ["+10 thức ăn bậc 3", "+10 tier 3 food"],
  "ui.debug.granted": ["Đã cộng", "Granted"],
};

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../content/localization");
for (const [index, locale] of ["vi", "en"].entries()) {
  const table = Object.fromEntries(Object.entries(strings).map(([key, values]) => [key, values[index]]).sort(([a], [b]) => a.localeCompare(b)));
  writeFileSync(`${root}/${locale}.ui.json`, JSON.stringify(table, null, 2) + "\n", "utf8");
}
console.log(`ui strings: ${Object.keys(strings).length} keys x 2 locales`);
