CREATE TABLE accounts (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(254) UNIQUE,
    password_hash VARCHAR(256),
    display_name VARCHAR(64) NOT NULL,
    kind VARCHAR(16) NOT NULL,
    roles VARCHAR(512) NOT NULL,
    banned_until BIGINT,
    created_at BIGINT NOT NULL
);

CREATE TABLE saves (
    account_id VARCHAR(36) NOT NULL,
    slot VARCHAR(32) NOT NULL,
    revision BIGINT NOT NULL,
    body TEXT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (account_id, slot)
);

CREATE TABLE save_history (
    id VARCHAR(36) PRIMARY KEY,
    account_id VARCHAR(36) NOT NULL,
    slot VARCHAR(32) NOT NULL,
    revision BIGINT NOT NULL,
    body TEXT NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE TABLE content_releases (
    version VARCHAR(64) PRIMARY KEY,
    sha256 VARCHAR(64) NOT NULL,
    body TEXT NOT NULL,
    bytes BIGINT NOT NULL,
    records INT NOT NULL,
    published_by VARCHAR(36) NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE TABLE content_channels (
    env VARCHAR(16) PRIMARY KEY,
    version VARCHAR(64) NOT NULL,
    promoted_by VARCHAR(36) NOT NULL,
    promoted_at BIGINT NOT NULL
);

CREATE TABLE telemetry_events (
    id VARCHAR(36) PRIMARY KEY,
    account_id VARCHAR(36),
    name VARCHAR(64) NOT NULL,
    payload TEXT NOT NULL,
    client_version VARCHAR(32),
    created_at BIGINT NOT NULL
);

CREATE TABLE audit_log (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id VARCHAR(36) PRIMARY KEY,
    actor_id VARCHAR(36) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target VARCHAR(128) NOT NULL,
    reason VARCHAR(512) NOT NULL,
    payload TEXT NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE TABLE mail (
    id VARCHAR(36) PRIMARY KEY,
    account_id VARCHAR(36) NOT NULL,
    subject VARCHAR(128) NOT NULL,
    grants TEXT NOT NULL,
    claimed BOOLEAN NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE TABLE battle_validations (
    id VARCHAR(36) PRIMARY KEY,
    account_id VARCHAR(36) NOT NULL,
    encounter_id VARCHAR(128) NOT NULL,
    claimed_outcome VARCHAR(16) NOT NULL,
    replayed_outcome VARCHAR(16) NOT NULL,
    valid BOOLEAN NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE TABLE agent_runs (
    id VARCHAR(36) PRIMARY KEY,
    mode VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    visited INT NOT NULL,
    registered INT NOT NULL,
    launch_percent DOUBLE PRECISION NOT NULL,
    report TEXT NOT NULL,
    uploaded_by VARCHAR(36) NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE INDEX telemetry_events_name ON telemetry_events (name);
CREATE INDEX audit_log_target ON audit_log (target);
CREATE INDEX mail_account ON mail (account_id);
